name: Setup Node.js environment
on: workflow_dispatch
jobs:
  setup-node:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2

            
