---
name: Setup Node.js
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18.19.0
          cache: 'npm'
          cache-dependency-path: 'subdir/package-lock.json'
      - run: npm install
      - run: npm test
      - run: npm install grunt --save-dev

                                                              
